import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className="bg-gray-900 h-screen w-screen">01</div>
        <div className="bg-gray-200 h-screen w-screen">02</div>
        <div className="bg-gray-800 h-screen w-screen">03</div>
        <div className="bg-gray-100 h-screen w-screen">04</div>
        <div className="bg-gray-700 h-screen w-screen">05</div> */}
        <div className="snap-y snap-mandatory h-screen w-screen overflow-scroll">
          <div className="snap-start bg-amber-200 w-screen h-screen flex items-center justify-center text-8xl">
            1
          </div>
          <div className="snap-start bg-teal-200 w-screen h-screen flex items-center justify-center text-8xl">
            2
          </div>
          <div className="snap-start bg-cyan-200 w-screen h-screen flex items-center justify-center text-8xl">
            3
          </div>
          <div className="snap-start bg-gray-200 w-screen h-screen flex items-center justify-center text-8xl">
            4
          </div>
        </div>
      </main>
    </>
  );
}
