import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>KuHell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="snap-y snap-mandatory h-screen w-screen overflow-scroll scrollbar-hide">
          <div className="snap-start bg-amber-200 w-screen h-screen flex items-center justify-center text-8xl"></div>
          <Link href="/about">
            <div className="snap-start bg-teal-200 w-screen h-screen flex items-center justify-center text-8xl"></div>
          </Link>
          <Link href="/blog">
            <div className="snap-start bg-gray-200 w-screen h-screen flex items-center justify-center text-8xl"></div>
          </Link>
          <Link href="/contact">
            <div className="snap-start bg-amber-200 w-screen h-screen flex items-center justify-center text-8xl"></div>
          </Link>
        </div>
      </main>
    </>
  );
}
